# Site settings
title: Mulberry Spring Farm
email: mulberryspringfarm@gmail.com
url: https://example.github.io
description: "Mulberry Spring Farm; a historical vacation destination nestled in the foothills of the Blue Ridge Mountains."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#fd5c63'

# Footer settings
footer: Eight Ten Labs LLC

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/people/Mulberry-Spring-Farm/100009961363563


# Build settings
markdown: kramdown
permalink: pretty
